import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillGithub, AiOutlineMail } from "react-icons/ai";
import Image from "next/image";
import sanjay from "../public/sanjay.jpg";
import design from "../public/design.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Sanjay's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white text-black px-10 md:px-20 lg:px-40 dark:bg-gray-800 dark:text-white ">
        <section className="min-h-screen pb-10">
          <nav className="py-10 mb-12 flex justify-between">
            <a href="localhost:3000">
              <h1 className="text-xl font-burtons">sanjaynatesan</h1>
            </a>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r to-cyan-500 from-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Sanjay Natesan
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">
              Developer. Data Scientist. Artist.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
              Hey! I'm Sanjay, a student at Columbia University studying
              Computer Science and Economics. Welcome to my website, where you
              can get a glimpse into my work in CS and Music (and somtimes,
              their intersection!) Feel free to explore, and don't hesitate to
              reach out to me at my email, found below! Happy travels :)
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <a href="https://www.linkedin.com/in/sanjaynatesan" target="_blank">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/sanjaynatesan" target="_blank">
              <AiFillGithub />
            </a>
            <a href="mailto:sanjay.natesan@columbia.edu">
              <AiOutlineMail />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={sanjay} fill />
          </div>
        </section>

        <section className="pb-10">
          <div>
            <h3 className="text-3xl py-1">Skills</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              In Computer Science, I have experience from several various
              ventures in prominent research institutions such as{" "}
              <span className="text-teal-600 dark:text-teal-500">
                The Rockefeller University, Columbia University Irving Medical
                Center, and the Cary Institute of Ecosystem Studies
              </span>
              , where I have worked in computational biology and AI/ML
              supervised learning devlopment. I also have been working as a
              freelance developer.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Some relevant coursework I have completed includes{" "}
              <span className="text-teal-600 dark:text-teal-500">
                Computation Linear Algebra, Artificial Intelligence,
                Multivariable Calculus, Statistics, Data Structures and
                Algorithms in Java, Advanced Programming in C, and Fundamentals
                of Computer Systems
              </span>
              .
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white pb-5">
              Here are some skills I have developed from these experiences.
            </p>
          </div>
          <div
            className="grid lg:grid-cols-3 md:grid-cols-2 gap-8"
          >
            <div className="relative text-center justify-center h-auto w-full shadow-xl shadow-gray-400 rounded-xl p-4">
              <Image
                src={design}
                width={100}
                height={100}
                className=" mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Backend Programming and Frameworks
              </h3>
              <h4 className="py-4 text-teal-600">
                Some backend programming languages and frameworks I have used
              </h4>
              <p className="text-gray-800 dark:text-white py-1">Python</p>
              <p className="text-gray-800 dark:text-white py-1">Java</p>
              <p className="text-gray-800 dark:text-white py-1">C/C#</p>
              <p className="text-gray-800 dark:text-white py-1">Flask</p>
              <p className="text-gray-800 dark:text-white py-1">Django</p>
            </div>
            <div className="relative text-center justify-center h-auto w-full shadow-xl shadow-gray-400 rounded-xl p-4">
              <Image
                src={design}
                width={100}
                height={100}
                className=" mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Frontend Programming
              </h3>
              <h4 className="py-4 text-teal-600">
                Some frontend programming languages I have used
              </h4>
              <p className="text-gray-800 dark:text-white py-1">HTML/CSS</p>
              <p className="text-gray-800 dark:text-white py-1">JavaScript</p>
              <p className="text-gray-800 dark:text-white py-1">React</p>
              <p className="text-gray-800 dark:text-white py-1">Node.js</p>
              <p className="text-gray-800 dark:text-white py-1">Swift/XCode</p>
            </div>
            <div className="relative text-center justify-center h-auto w-full shadow-xl shadow-gray-400 rounded-xl p-4">
              <Image
                src={design}
                width={100}
                height={100}
                className=" mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Statistical Computing
              </h3>
              <h4 className="py-4 text-teal-600">
                Some staticial computing languages and packages I have used
              </h4>
              <p className="text-gray-800 dark:text-white py-1">Python</p>
              <p className="text-gray-800 dark:text-white py-1">R</p>
              <p className="text-gray-800 dark:text-white py-1">scikit learn / sciPy</p>
              <p className="text-gray-800 dark:text-white py-1">ggplot2</p>
              <p className="text-gray-800 dark:text-white py-1">dplyr/tidyr/shiny</p>
              <p className="text-gray-800 dark:text-white py-1">pandas/matplotlib</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Some projects I have recently completed...
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={design}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={design}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
