import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { AiFillGithub, AiFillLinkedin, AiOutlineMail } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  SiAmazonaws,
  SiChakraui,
  SiCplusplus,
  SiCss3,
  SiDjango,
  SiFirebase,
  SiFlask,
  SiGit,
  SiGithub,
  SiGooglechrome,
  SiHeroku,
  SiHtml5,
  SiJava,
  SiJavascript,
  SiNextdotjs,
  SiPostman,
  SiPython,
  SiReact,
  SiRstudio,
  SiSwift,
  SiTailwindcss,
  SiVercel,
} from "react-icons/si";
import { IoIosPaper } from "react-icons/io";
import { GiHamburgerMenu } from "react-icons/gi";
import Typed from "react-typed";
import design from "../public/img/design.png";
import sanjay from "../public/img/sanjay.jpg";
import covres from "../public/img/covid-research.jpeg";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [showMenu, setShowMenu] = useState(false);

  return (
    <div className={`relative z-0 ${darkMode ? "dark" : ""}`}>
      <Head>
        <title>Sanjay's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {showMenu && (
        <div className="flex fixed items-center sm:hidden inset-y-0 left-0 z-10 p-6 w-1/2 bg-gray-100 top-0 lg:left-0 lg:w-60  peer-focus:left-0 peer:transition ease-out delay-150 duration-200 dark:bg-gray-700 dark:text-white">
          <a href="localhost:3000" className=" w-max">
            <h1 className="absolute inset-y-10 text-xl py-2 font-burtons text-black dark:text-white">
              sanjaynatesan
            </h1>
          </a>
          <Link
            className="absolute inset-y-20 px-4 py-2 text-black dark:text-white"
            href="/#skills"
          >
            Skills
          </Link>
          <Link
            className="absolute inset-y-28 px-4 py-2 text-black dark:text-white"
            href="/#projects"
          >
            Projects
          </Link>
          <Link
            className="absolute inset-y-36 px-4 py-2 text-black dark:text-white"
            href="/music"
          >
            Music Page
          </Link>
        </div>
      )}

      <main className="bg-white text-black px-10 md:px-20 dark:bg-gray-800 dark:text-white ">
        <section className="min-h-screen pb-32">
          <nav className="py-8 mb-12 flex justify-between">
            <a href="localhost:3000">
              <h1 className="text-xl py-2 font-burtons">sanjaynatesan</h1>
            </a>
            <ul className="hidden items-center sm:flex">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <Link
                className=" px-4 py-2 text-black dark:text-white ml-5"
                href="/#skills"
              >
                Skills
              </Link>
              <li>
                <Link
                  className=" px-4 py-2 text-black dark:text-white"
                  href="/#projects"
                >
                  Projects
                </Link>
                <Link
                  className="bg-gradient-to-r to-cyan-500 from-teal-500 text-white px-4 py-2 rounded-md"
                  href="/music"
                >
                  Music Page
                </Link>
              </li>
            </ul>
            <ul className="flex items-center sm:hidden">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <button
                className="px-4 text-6xl text-gray dark:text-white rounded-md"
                onClick={() => {
                  setShowMenu(!showMenu);
                }}
              >
                <GiHamburgerMenu className="px-4 text-black dark:text-white" />
              </button>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Sanjay Natesan
            </h2>
            <p className="text-2xl py-2 md:text-3xl font-light">
              <span className="text-slider-items"></span>
              <strong className="text-slider">
                <Typed
                  strings={["Developer", "Data Scientist", "Artist"]}
                  typeSpeed={100}
                  backDelay={1100}
                  backSpeed={50}
                  loop
                />
              </strong>
            </p>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white">
              Hey! I'm Sanjay, a student at Columbia University studying
              Computer Science and Economics. Welcome to my website, where you
              can get a glimpse into my work in CS and Music (and sometimes,
              their intersection!) Feel free to explore, and don't hesitate to
              reach out to me at my email, found below! Happy travels :)
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <a href="https://www.linkedin.com/in/sanjaynatesan" target="_blank">
              <AiFillLinkedin />
            </a>
            <a href="https://github.com/sanjaynatesan" target="_blank">
              <AiFillGithub />
            </a>
            <a href="mailto:sanjay.natesan@columbia.edu">
              <AiOutlineMail />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={sanjay} fill />
          </div>
        </section>

        <section className="text-center" id="skills">
          <div>
            <h3 className="text-5xl py-1 text-teal-600">Skills</h3>
          </div>
          <div className="text-xl md:text-2xl py-2 leading-8 text-gray-600 dark:text-white pb-5">
            Languages
          </div>
          <div className="text-5xl grid xl:grid-cols-8 sm:grid-cols-4 grid-cols-2 gap-10 py-4 xl:max-w-4xl sm:max-w-md max-w-[200px] mx-auto text-gray-100 dark:text-teal-600">
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiPython className="mx-auto" />
                <p className="pt-2 text-sm">Python</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiJava className="mx-auto" />
                <p className="pt-2 text-sm">Java</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiRstudio className="mx-auto" />
                <p className="pt-2 text-sm">R</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiCplusplus className="mx-auto" />
                <p className="pt-2 text-sm">C / C++</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiJavascript className="mx-auto" />
                <p className="pt-2 text-sm">JavaScript</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiHtml5 className="mx-auto" />
                <p className="pt-2 text-sm">HTML 5</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiCss3 className="mx-auto" />
                <p className="pt-2 text-sm">CSS 3</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiSwift className="mx-auto" />
                <p className="pt-2 text-sm">Swift</p>
              </div>
            </div>
          </div>
          <div className="text-xl md:text-2xl py-2 leading-8 text-gray-600 dark:text-white pb-5">
            Frontend, UI Libraries, and Frameworks
          </div>
          <div className="text-5xl grid xl:grid-cols-6 sm:grid-cols-3 grid-cols-2 gap-10 py-4 xl:max-w-2xl sm:max-w-xs max-w-[200px] mx-auto text-gray-100 dark:text-teal-600">
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiReact className="mx-auto" />
                <p className="pt-2 text-sm">React</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiNextdotjs className="mx-auto" />
                <p className="pt-2 text-sm">Next.js</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiChakraui className="mx-auto" />
                <p className="pt-2 text-sm">Chakra UI</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiTailwindcss className="mx-auto" />
                <p className="pt-2 text-sm">Tailwind CSS</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiFlask className="mx-auto" />
                <p className="pt-2 text-sm">Flask</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiDjango className="mx-auto" />
                <p className="pt-2 text-sm">Django</p>
              </div>
            </div>
          </div>
          <div className="text-xl md:text-2xl py-2 leading-8 text-gray-600 dark:text-white pb-5">
            Production Testing and Tools
          </div>
          <div className="text-5xl grid xl:grid-cols-6 sm:grid-cols-3 grid-cols-2 gap-10 py-4 xl:max-w-2xl sm:max-w-xs max-w-[200px] mx-auto text-gray-100 dark:text-teal-600">
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiFirebase className="mx-auto" />
                <p className="pt-2 text-sm">Firebase</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiHeroku className="mx-auto" />
                <p className="pt-2 text-sm">Heroku</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiVercel className="mx-auto" />
                <p className="pt-2 text-sm">Vercel</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiAmazonaws className="mx-auto" />
                <p className="pt-2 text-sm">AWS</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiGit className="mx-auto" />
                <p className="pt-2 text-sm">Git</p>
              </div>
            </div>
            <div className="flex bg-teal-600 dark:bg-white p-3 w-24 h-32 text-center rounded-md mx-auto hover:scale-105 ease-in duration-300">
              <div className="m-auto">
                <SiPostman className="mx-auto" />
                <p className="pt-2 text-sm">Postman</p>
              </div>
            </div>
          </div>
        </section>

        <section className="pt-24 pb-10" id="projects">
          <div className="text-center">
            <h3 className="text-3xl py-1 text-teal-600">Select Projects</h3>
          </div>
          <div className="grid xl:grid-cols-3 md:grid-cols-2 gap-8">
            <div className="relative text-center justify-center h-auto w-full shadow-xl shadow-gray-400 rounded-xl p-4 hover:scale-105 ease-in duration-300">
              <h3 className=" text-2xl text-teal-600 font-medium pt-8 pb-2">
                Manhattan Virome Project
              </h3>
              <h4 className="py-4">
                Helped investigate the transmission of respiratory viruses
                throughout urban Manhattan to develop significant understanding
                into transmission dynamics, and improving respiratory disease
                model simulation and forecast. Contributed to development of
                website describing findings.
              </h4>
              <div class="flex flex-wrap gap-3 text-red-500 dark:text-red-400">
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  Python
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  JavaScript
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  Django
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  CSS
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  AWS
                </div>
              </div>
              <div className="text-3xl flex justify-center gap-7 py-4 text-gray-600 dark:text-white">
                <a href="http://18.204.18.242:1234/" target="_blank">
                  <SiGooglechrome />
                </a>
                <a
                  href="https://genomemedicine.biomedcentral.com/"
                  target="_blank"
                >
                  <IoIosPaper />
                </a>
              </div>
            </div>
            <div className="relative text-center justify-center h-auto w-full shadow-xl shadow-gray-400 rounded-xl p-4 hover:scale-105 ease-in duration-300">
              <h3 className=" text-2xl text-teal-600 font-medium pt-8 pb-2">
                Personal Website
              </h3>
              <h4 className="py-4">
                Created this personal website from scratch using Next.js, React,
                and Tailwind CSS. This website was deployed using Vercel.
              </h4>
              <div class="flex flex-wrap gap-3 text-red-500 dark:text-red-400">
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  Next.js
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  React
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  Tailwind CSS
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  Vercel
                </div>
              </div>
              <div className="text-3xl flex justify-center gap-7 py-4 text-gray-600 dark:text-white">
                <a href="http://sanjaynatesan.com/" target="_blank">
                  <SiGooglechrome />
                </a>
                <a
                  href="https://github.com/sanjaynatesan/website"
                  target="_blank"
                >
                  <SiGithub />
                </a>
              </div>
            </div>
            <div className="relative text-center justify-center h-auto w-full shadow-xl shadow-gray-400 rounded-xl p-4 hover:scale-105 ease-in duration-300">
              <h3 className=" text-2xl text-teal-600 font-medium pt-8 pb-2">
                HTTP Server
              </h3>
              <h4 className="py-4">
                Built an HTTP web server from scratch, using socket programming
                in C to serve static HTML pages and dynamic pages queried from a
                database lookup server upon receiving user input text.
              </h4>
              <div class="flex flex-wrap gap-3 text-red-500 dark:text-red-400">
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  C
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  Linux
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  Git
                </div>
              </div>
              <div className="text-3xl flex justify-center gap-7 py-4 text-gray-600 dark:text-white">
                <a
                  href="https://gist.github.com/sanjaynatesan/4e65a9d99bef53e8dfb4f0811bf50d7c"
                  target="_blank"
                >
                  <SiGithub />
                </a>
              </div>
            </div>
            <div className="relative text-center justify-center h-auto w-full shadow-xl shadow-gray-400 rounded-xl p-4 hover:scale-105 ease-in duration-300">
              <h3 className=" text-2xl text-teal-600 font-medium pt-8 pb-2">
                SimplifiEdu SAT Analysis Tool
              </h3>
              <h4 className="py-4">
                Launched a full-stack web application a developed scoring
                algorithm to provide critical evaluation and feedback to
                students. Optimized code for improved site navigation, response,
                and user experience.
              </h4>
              <div class="flex flex-wrap gap-3 text-red-500 dark:text-red-400">
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  Python
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  React
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  Flask
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  ChakraUI
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  Heroku
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  EmailJS
                </div>
              </div>
              <div className="text-3xl flex justify-center gap-7 py-4 text-gray-600 dark:text-white">
                <a
                  href="https://ingenius-diagnostics.herokuapp.com/"
                  target="_blank"
                >
                  <SiGooglechrome />
                </a>
              </div>
            </div>
            <div className="relative text-center justify-center h-auto w-full shadow-xl shadow-gray-400 rounded-xl p-4 hover:scale-105 ease-in duration-300">
              <h3 className=" text-2xl text-teal-600 font-medium pt-8 pb-2">
                Rockefeller University - COVID-19 Vaccination Rate Analysis
              </h3>
              <h4 className="py-4">
                As part of the 2020 Rockefeller University Summer Science
                Research Program, conducted a statistical analysis using R
                (including libraries like limma, tidyverse, and edgeR) and
                explored plausible relationships between SARS-CoV-2 antibody
                binding, vaccination rates, and demographics.
              </h4>
              <div class="flex flex-wrap gap-3 text-red-500 dark:text-red-400">
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  R
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  Python
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  limma
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  tidyverse
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  edgeR
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  ggplot2
                </div>
              </div>
              <div className="text-3xl flex justify-center gap-7 py-4 text-gray-600 dark:text-white">
                <a href="http://sanjaynatesan.com/" target="_blank">
                  <SiGithub />
                </a>
              </div>
            </div>
            <div className="relative text-center justify-center h-auto w-full shadow-xl shadow-gray-400 rounded-xl p-4 hover:scale-105 ease-in duration-300">
              <h3 className=" text-2xl text-teal-600 font-medium pt-8 pb-2">
                Rockefeller University - COVID-19 Gene Analysis
              </h3>
              <h4 className="py-4">
                As part of the 2019 Rockefeller University Summer Science
                Research Program, explored the relationship between COVID-19 and
                Gene Expression in patients testing positive for COVID, and
                identified several potential genetic indicators of the disease.
                These findings were later confirmed by other studies conducted
                in Qatar, the US, and Europe.
              </h4>
              <div class="flex flex-wrap gap-3 text-red-500 dark:text-red-400">
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  R
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  limma
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  tidyverse
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  edgeR
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  ggplot2
                </div>
              </div>
              <div className="text-3xl flex justify-center gap-7 py-4 text-gray-600 dark:text-white">
                <a href="http://sanjaynatesan.com/" target="_blank">
                  <SiGithub />
                </a>
              </div>
            </div>
            <div className="relative text-center justify-center h-auto w-full shadow-xl shadow-gray-400 rounded-xl p-4 hover:scale-105 ease-in duration-300">
              <h3 className=" text-2xl text-teal-600 font-medium pt-8 pb-2">
                Crimean-Congo Hemorrhagic Fever Analysis Project
              </h3>
              <h4 className="py-4">
                As part of the Han Lab at the Cary Institute of Ecosystem
                Studies, I led a comprehensive study on factors impacting the
                prevalence of CCHF in Southeastern Europe, employing statistical
                methods and R programming to identify correlation between
                environmental/social factors and infection rates.
              </h4>
              <div class="flex flex-wrap gap-3 text-red-500 dark:text-red-400">
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  R
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  limma
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  tidyverse
                </div>
                <div className=" px-1.5 py-0.5 rounded-full border-solid border-4 border-red-500 dark:border-red-400">
                  ggplot2
                </div>
              </div>
              <div className="text-3xl flex justify-center gap-7 py-4 text-gray-600 dark:text-white">
                <a
                  href="https://www.caryinstitute.org/news-insights/feature/team-cary-sanjay-natesan"
                  target="_blank"
                >
                  <IoIosPaper />
                </a>
              </div>
            </div>
          </div>
        </section>

        <section className="pt-32"></section>
      </main>
    </div>
  );
}

{
  /* <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              In Computer Science, I have experience from several various
              ventures in prominent research institutions such as{" "}
              <span className="text-teal-600 dark:text-teal-500">
                The Rockefeller University, Columbia University Irving Medical
                Center, and the Cary Institute of Ecosystem Studies
              </span>
              , where I have worked in computational biology and AI/ML
              supervised learning devlopment. I also have been working as a
              freelance developer.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white">
              Some relevant coursework I have completed include{" "}
              <span className="text-teal-600 dark:text-teal-500">
                Computation Linear Algebra, Artificial Intelligence,
                Multivariable Calculus, Statistics, Data Structures and
                Algorithms in Java, Advanced Programming in C, and Fundamentals
                of Computer Systems
              </span>
              .
            </p> */
}
